INSERT INTO US_JOB_DATA (City, Job, Exp_Sal, Role_Desc, Role, Type) VALUES
	('Austin','job','Exp_sal','Role_Desc','Role','Type')
	('Austin','job','Exp_sal','Role_Desc','Role','Type')
	('Austin','job','Exp_sal','Role_Desc','Role','Type')
	('Boston','job','Exp_sal','Role_Desc','Role','Type')
	('Boston','job','Exp_sal','Role_Desc','Role','Type')
	('Boston','job','Exp_sal','Role_Desc','Role','Type')
	('Charlotte','job','Exp_sal','Role_Desc','Role','Type')
	('Charlotte','job','Exp_sal','Role_Desc','Role','Type')
	('Charlotte','job','Exp_sal','Role_Desc','Role','Type')
	(‘Chicago’, ‘Artist’, ‘50000’, NULL, ‘Entry Level’, ‘Remote’),
	(‘Chicago’, ‘Doctor’, ‘130000, ‘Heal People’, ‘Senior Level’, ‘In Person’)
	('Chicago','job','Exp_sal','Role_Desc','Role','Type')
	('Cleveland','job','Exp_sal','Role_Desc','Role','Type')
	('Cleveland','job','Exp_sal','Role_Desc','Role','Type')
	('Cleveland','job','Exp_sal','Role_Desc','Role','Type')
	('Dallas','job','Exp_sal','Role_Desc','Role','Type')
	('Dallas','job','Exp_sal','Role_Desc','Role','Type')
	('Dallas','job','Exp_sal','Role_Desc','Role','Type')
	('Denver','job','Exp_sal','Role_Desc','Role','Type')
	('Denver','job','Exp_sal','Role_Desc','Role','Type')
	('Denver','job','Exp_sal','Role_Desc','Role','Type')
	('Houston','job','Exp_sal','Role_Desc','Role','Type')
	('Houston','job','Exp_sal','Role_Desc','Role','Type')
	('Houston','job','Exp_sal','Role_Desc','Role','Type')
	('Indianapolis','job','Exp_sal','Role_Desc','Role','Type')
	('Indianapolis','job','Exp_sal','Role_Desc','Role','Type')
	('Indianapolis','job','Exp_sal','Role_Desc','Role','Type')
	('Los Angeles','job','Exp_sal','Role_Desc','Role','Type')
	('Los Angeles','job','Exp_sal','Role_Desc','Role','Type')
	('Los Angeles','job','Exp_sal','Role_Desc','Role','Type')
	('Miami','job','Exp_sal','Role_Desc','Role','Type')
	('Miami','job','Exp_sal','Role_Desc','Role','Type')
	('Miami','job','Exp_sal','Role_Desc','Role','Type')
	('Nashville','job','Exp_sal','Role_Desc','Role','Type')
	('Nashville','job','Exp_sal','Role_Desc','Role','Type')
	('Nashville','job','Exp_sal','Role_Desc','Role','Type')
	('New York','job','Exp_sal','Role_Desc','Role','Type')
	('New York','job','Exp_sal','Role_Desc','Role','Type')
	('New York','job','Exp_sal','Role_Desc','Role','Type')
	('Philadelphia','job','Exp_sal','Role_Desc','Role','Type')
	('Philadelphia','job','Exp_sal','Role_Desc','Role','Type')
	('Philadelphia','job','Exp_sal','Role_Desc','Role','Type')
	('Phoenix','job','Exp_sal','Role_Desc','Role','Type')
	('Phoenix','job','Exp_sal','Role_Desc','Role','Type')
	('Phoenix','job','Exp_sal','Role_Desc','Role','Type')
	('Portland','job','Exp_sal','Role_Desc','Role','Type')
	('Portland','job','Exp_sal','Role_Desc','Role','Type')
	('Portland','job','Exp_sal','Role_Desc','Role','Type')
	('San Diego','job','Exp_sal','Role_Desc','Role','Type')
	('San Diego','job','Exp_sal','Role_Desc','Role','Type')
	('San Diego','job','Exp_sal','Role_Desc','Role','Type')
	('San Francisco','job','Exp_sal','Role_Desc','Role','Type')
	('San Francisco','job','Exp_sal','Role_Desc','Role','Type')
	('San Francisco','job','Exp_sal','Role_Desc','Role','Type')
	('Seattle','job','Exp_sal','Role_Desc','Role','Type')
	('Seattle','job','Exp_sal','Role_Desc','Role','Type')
	('Seattle','job','Exp_sal','Role_Desc','Role','Type')
	('Washington D.C','job','Exp_sal','Role_Desc','Role','Type')
	('Washington D.C','job','Exp_sal','Role_Desc','Role','Type')
	('Washington D.C','job','Exp_sal','Role_Desc','Role','Type');
